name: java springboot backend

on:
    push:
        paths:
            - 'backend/**'
    pull_request:
        paths:
            - 'backend/**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: setup jdk 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
        - name: Build with Maven
          run: cd backend && mvn clean install
        - name: Build with Maven
          run: cd backend && mvn clean install
        - name: Run tests
          run: cd backend && mvn test
            
            
    
            

