name: java springboot backend

on:
    push:
        paths:
            - 'backend/**'
    pull_request:
        paths:
            - 'backend/**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: setup jdk 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: maven
        - name: make keygen.sh executable
          run: cd backend && chmod u+x keygen.sh
        - name: run script for generate public and private key
          run: cd backend && ./keygen.sh
        - name: Build and Run Test
          run: cd backend && mvn --batch-mode package
            
            
    
            

